# Generated by Django 3.1.4 on 2021-09-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseproj', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notes',
            table='notes',
        ),
    ]
