# Generated by Django 3.1.4 on 2021-09-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseproj', '0003_sharedwith'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedwith',
            name='shared_user_id',
            field=models.CharField(max_length=100),
        ),
    ]
