# Generated by Django 3.1.4 on 2021-09-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseproj', '0004_auto_20210922_1656'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sharedwith',
            table='sharedwith',
        ),
    ]
