# Generated by Django 3.1.4 on 2021-09-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseproj', '0006_auto_20210922_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedwith',
            name='noteid',
            field=models.IntegerField(default=0),
        ),
    ]
