# Generated by Django 3.1.4 on 2021-09-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseproj', '0007_sharedwith_noteid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedwith',
            name='note_desc',
        ),
        migrations.RemoveField(
            model_name='sharedwith',
            name='note_title',
        ),
    ]
